# Site settings
timezone: Africa/Johannesburg
title: Incomplete Developer
tagline: Modern Software Development (aahh that would mean AI, right?)
description: >
  A developer who is very happy to be eating banana but pretends to be knowledgeable about software development.

url: "https://mpholoane-bapela.github.io"
baseurl: ""

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

github:
  username: mpholoane-bapela

social:
  name: Mpholoane Bapela
  email: 
  links:
    - https://github.com/mpholoane-bapela
    - https://www.linkedin.com/in/mpholoane-bapela-3349146a
    - https://www.youtube.com/@IncompleteDeveloper
    - https://www.upwork.com/freelancers/~011db411a046eb1c2a?mp_source=share

avatar: /assets/img/avatar.png

# Permalink
permalink: /:title/

theme_mode: # light or dark, leave empty for auto

toc: true

comments:
  active:

paginate: 10
